# This is a basic workflow to help you get started with Actions

name: Stadia Games Bot - Update games list

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # At minute 59 past hour 6, 15, and 21 - more info: https://crontab.guru/#59_6,15,21_*_*_*
    - cron:  '59 6,15,21 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "script"
  script:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Run script
        env:
          TELEGRAM_BOT_APIKEY: ${{ secrets.TELEGRAM_BOT_APIKEY }}
          TELEGRAM_CHAT_ID_LIST: ${{ secrets.TELEGRAM_CHAT_ID_LIST }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_KEY: ${{ secrets.TWITTER_ACCESS_KEY }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: kotlinc -script ./stadia-games-bot.main.kts

      # Commit modified files
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Stadia Games: Update list, changelog, and new details (using Github Action)" || true

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
